version: 2.1

jobs:
  build:
    docker:
      - image: ruby:latest

    working_directory: /path/to/your/ruby/project

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Bundler
          command: gem install bundler

      - run:
          name: Install dependencies
          command: bundle install

      - run:
          name: Run RuboCop
          command: rubocop main.rb

      # Run tests
      - run:
          name: Run tests
          command: bundle exec ruby test.rb

workflows:
  version: 2
  build:
    jobs:
      - build
