version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7

    steps:
      - checkout

      - run:
          name: Create .bundle directory
          command: mkdir -p .bundle

      - run:
          name: Update Bundler
          command: gem update bundler

      - run:
          name: Install Dependencies
          command: bundle install --path=vendor/bundle

      - run:
          name: Run Tests
          command: PATH=$PATH:vendor/bundle/bin bundle exec rspec
